default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] || Rails.application.credentials.dig(:database, :url) %>
  database: ai_clin_cds_development

test:
  <<: *default
  url: <%= ENV["TEST_DATABASE_URL"] %>
  database: ai_clin_cds_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] || Rails.application.credentials.dig(:database, :url) %>
  database: ai_clin_cds_production